"""add domain_type

Revision ID: bb9a75e5718e
Revises: e1183f345fd1
Create Date: 2026-01-13 17:07:23.692607

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb9a75e5718e"
down_revision: str | Sequence[str] | None = "e1183f345fd1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "domain_info",
        sa.Column(
            "domain_type",
            sa.Enum("root", "subdomain", name="domaintype"),
            server_default="subdomain",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("domain_info", "domain_type")
    # ### end Alembic commands ###
