"""remove subdomains add dns_settings

Revision ID: e1183f345fd1
Revises: d8eff2462bf7
Create Date: 2026-01-12 13:15:19.566199

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "e1183f345fd1"
down_revision: str | Sequence[str] | None = "d8eff2462bf7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("domain_info", sa.Column("dns_settings", sa.JSON(), nullable=True))
    op.drop_column("domain_info", "subdomains")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("domain_info", sa.Column("subdomains", sqlite.JSON(), nullable=True))
    op.drop_column("domain_info", "dns_settings")
    # ### end Alembic commands ###
